### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by siny1998** [YutingHe-list/GVSL#1]
Hi, thank you very much for the code you provided. I would like to fine-tune the pre-trained model on my own dataset. Will you be making your pre-trained model weights available? Thanks.

**Comment by YutingHe-list** [comment]
Thanks for your interest in our work. Yes, we will, maybe next week. We will also gradually open some pre-trained models on other data sets. Welcome to pay attention to our work.

**Comment by siny1998** [comment]
Thanks for your reply. I am looking forward to it.

**Comment by Adoreeeeee** [comment]
Hello! I'd like to ask which model file you are currently using to train the pre-trained model that you are currently publicing
