### ISSUE TITLE
Which file in SMB dataset should I download?

### ISSUE THREAD

**Issue by RightL** [YutingHe-list/GVSL#2]
Hi, thank you for the code. I'm trying to download the SMB dataset but found many files on the download page. I'm wondering which one should I download.
![image](https://user-images.githubusercontent.com/9251452/223944464-fe7d3b94-62a3-468d-ac2a-3d95179f82f8.png)

**Comment by YutingHe-list** [comment]
Thanks for your question. It is true that the files of this data set are very confusing. You can download all these files and you will find only 103 data with segmentation labels can be used.
